name: foodieguide/iptvsearch

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp ffmpeg sed nmap
        pwd
        which yt-dlp

    - name: Run hoteliptv.sh
      run: |
        cd $GITHUB_WORKSPACE/foodieguide
        bash ./hoteliptv.sh
        for file in $(find . -name '*_hotel_foodieguide.txt'); do
          bash ../speedtest/rtp2m3u.sh "$file"
        done

    # - name: Run foodieguide.sh
    #   run: |
    #     cd $GITHUB_WORKSPACE/foodieguide
    #     bash ./foodieguide.sh
    #     for file in $(find . -name '*_foodieguide.txt'); do
    #       bash ../speedtest/rtp2m3u.sh "$file"
    #     done

    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update foodieguide/iptv"
        branch: main  # Commit to the main branch
