name: foodieguide/iptvsearch

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp ffmpeg sed nmap
        pwd
        which yt-dlp

    - name: Run foodieguide.sh
      #working-directory: iptv/foodieguide
      run: |
        git pull origin main
        cd $GITHUB_WORKSPACE/foodieguide
        bash ./foodieguide.sh
        bash ../speedtest/rtp2m3u.sh './taiwan_foodieguide.txt'
        

    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull --rebase origin main
        git add .
        git status
        git commit -m "Update foodieguide iptv "
        git push
