name: gangaotai_gat

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp ffmpeg sed nmap
        pip install --upgrade yt-dlp
        pwd
        which yt-dlp

    - name: Run gangaotai_gat.sh
      run: |
        cd $GITHUB_WORKSPACE/gangaotai
        bash ./gangaotai_gat.sh
        for file in $(find ../output/ -name '*_gat.txt'); do
          bash ../rtp2m3u.sh "$file"
        done

    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update foodieguide/iptv"
        branch: main  # Commit to the main branch
