name: Update ITV M3U

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update_itv_m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download itv.m3u content
        run: curl -L -o itv.m3u https://tv.wangqifei.eu.org/itv.m3u

      - name: Check for #EXTM3U in itv.m3u
        run: |
          if ! grep -q '^#EXTM3U' itv.m3u; then
            echo "File does not contain #EXTM3U, exiting..."
            exit 1
          fi

      - name: Process itv.m3u file
        run: |
          input_file="itv.m3u"
          output_file="processed_itv.m3u"
          temp_file="tmp_file.m3u8"

          # 1. 使用 cat 命令去除空行写入临时文件
          cat "$input_file" > "$temp_file"

          # 2. 将时间戳覆盖到 output 文件，修改epg源
          echo "# $(date)" > "$output_file"

          # 3. 使用 awk 将包含 EXTM3U 的行追加到 output 文件，并在临时文件中删除
          awk '/EXTM3U/ {print $0;}' "$temp_file" > "$output_file"
          sed -i 's|^#EXTM3U x-tvg-url="[^"]*"|#EXTM3U x-tvg-url="https://live.fanmingming.com/e.xml"|' "$output_file"
          echo "# $(date)" >> "$output_file"
          echo "" >> "$output_file"
          sed -i '/EXTM3U/d' "$temp_file"

          # 4. 使用 awk 将包含 HEVC 的行及其下一行追加到 output 文件，并在临时文件中删除
          awk '/HEVC/ {print $0; getline; print $0; print ""}' "$temp_file" >> "$output_file"
          sed -i '/HEVC/,+1d' "$temp_file"

          # 5. 使用 awk 将包含 FPS 的行及其下一行追加到 output 文件，并在临时文件中删除
          awk '/FPS/ {print $0; getline; print $0;print ""}' "$temp_file" >> "$output_file"
          sed -i '/FPS/,+1d' "$temp_file"

          # 6. 将临时文件中剩余的内容追加到 output 文件
          cat "$temp_file" >> "$output_file"

          # 7. 追加台湾频道
          sed '1d' "speedtest/template/taiwan.m3u" >> "$output_file"

          # 8. 增加香港频道
          curl -L -o sichuan_hongkong.tmp https://mirror.ghproxy.com/raw.githubusercontent.com/redrainl/iptv/main/speedtest/txt/Sichuan_333.txt
          sed -i '/凤凰|CHANNEL-V|CHANNELV|星空/,+1d' "$output_file"
          awk '/凤凰|CHANNEL-V|CHANNELV|星空(?!精选)/ {print $0;}' "sichuan_hongkong.tmp" > "./hongkong.tmp"
          sort "./hongkong.tmp" | uniq > "./hongkong.tmp.tmp" && mv "./hongkong.tmp.tmp" "./hongkong.tmp"
          echo '============== hongkong.tmp ============='
          cat "./hongkong.tmp"
          bash ./speedtest/rtp2m3u.sh "./hongkong.tmp"
          echo "========= hongkong.m3u =========="
          cat "./hongkong.m3u"
          sed -i '/凤凰\|CHANNEL-V\|星空\|CHANNELV/ s/group-title="[^"]*"/group-title="香港"/g' "./hongkong.m3u"
          cat "./hongkong.m3u" >> "$output_file"
          rm "sichuan_hongkong.tmp" "./hongkong.tmp" "./hongkong.m3u"

          # 9. 整理 动画 频道
          echo "" > temp.txt
          sed -n '/CCTV 14 HEVC\|少儿\|儿童\|动画\|动漫\|動畫\|動漫\|哆啦A梦\|HakkaTV\|超人\|nickjr\|Nickelodeon/{N;s/\(group-title="\)[^"]*/\1动画/;p;}' "$output_file" >> temp.txt
          cat temp.txt >> "$output_file"
          rm temp.txt

          # 10. 英语频道
          sed -n '/英語\|VOA/{N;s/\(group-title="\)[^"]*/\1英语/;p;}' "$output_file" >> temp.txt
          cat temp.txt >> "$output_file"
          rm temp.txt

          # 多个空格转为1个空格,多个空行合并为一个空行
          sed 's/ \+/ /g
