name: Run thetvapp.py

on: 
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run thetvapp.py with default channel
      run: |
        echo "1" | python thetvapp.py > thetvapp.list

    # - name: Run thetvapp.py for all channels
    #   if: always()
    #   run: |
    #     for i in {1..118}; do
    #       echo "$i" | python thetvapp.py >> result.txt
    #     done


      - name: Stage changes
        run: |
          echo "Staging changes..."
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update thetvapp.list"
          branch: main  # Commit to the main branch
