name: Run thetvapp.py

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run thetvapp.py
      run: |
        python thetvapp.py

    # - name: Upload thetvapp.py outputfile
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: playlist
    #     path: playlist.txt

    - name: process playlist.txt
      run: |
        sed -i 's/an/tx/g' playlist.txt
        mv playlist.txt speedtest/thetvapp.txt
        bash ./speedtest/rtp2m3u.sh "thetvapp.txt"

    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update thetvapp.list"
        branch: main  # Commit to the main branch
