name: Daily Job_fofa

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
      #sudo apt-get install -y yt-dlp sed nmap

    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./fofa_all.sh
        bash ./rtp2m3u.sh

    - name: Run add 凤凰-星空-channel v to itv.m3u
      #working-directory: iptv
      run: |
        cd $GITHUB_WORKSPACE
        awk '/凤凰|CHANNEL-V|星空/ {print $0; getline; print $0}' "$output_file" >> temp.txt
        # sed -n '/凤凰|CHANNEL-V|星空/{N;s/\(group-title="\)[^"]*/\1香港;p;}' "$output_file" >> temp.txt

    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git commit -m "Update results_fofa and add 凤凰|星空|channelV to itv.m3u"
        git push
