name: Daily Job_fofa

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
        which yt-dlp

    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./multi.sh
        # bash ./fofa_all.sh
        bash ./fofa.sh
        bash ./rtp2m3u.sh './zubo_fofa.txt'

    # - name: Run add 凤凰-星空-channel v to itv.m3u
      # working-directory: iptv
      # run: |
        # cd $GITHUB_WORKSPACE
        # sed -i '/凤凰|CHANNEL-V|星空/,+1d' "./itv.m3u"
        # awk '/凤凰|CHANNEL-V|星空/ {print $0; getline; print $0;}' "./speedtest/zubo_fofa.m3u" > "./hongkong.tmp"
        # cat "./hongkong.tmp" >> "./itv.m3u"
        # sed -i '/凤凰\|CHANNEL-V\|星空/ s/group-title="[^"]*"/group-title="香港"/g' "./itv.m3u"

    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git commit -m "Update results_fofa "
        git push
